name: "Alpine Linux: Build toolbx images for PRs"

permissions: read-all

on:
  pull_request:
    branches:
      - main
    paths:
      - alpine/**
      - .github/workflows/alpine-pr.yaml

env:
  distro: 'alpine'
  distro_pretty: 'Alpine Linux'
  latest_release: '3.19'

jobs:
  build-images:
    strategy:
      matrix:
        release: ['3.16', '3.17', '3.18', '3.19', 'edge']

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build ${{ env.distro_pretty }} ${{ matrix.release }} toolbox image
        uses: docker/build-push-action@v3
        with:
          context: ${{ env.distro }}/${{ matrix.release }}
          file: ${{ env.distro }}/${{ matrix.release }}/Containerfile
          platforms: linux/amd64,linux/arm64
          push: false
          no-cache: true
          tags: quay.io/toolbx-images/${{ env.distro }}-toolbox:${{ matrix.release }}
