name: "Arch Linux: Build toolbx image for PRs"

permissions: read-all

on:
  pull_request:
    branches:
      - main
    paths:
      - archlinux/**
      - .github/workflows/archlinux-pr.yaml

env:
  distro: 'archlinux'
  distro_pretty: 'Arch Linux'
jobs:
  build-and-push-images:
    name: Build and push images

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build ${{ env.distro_pretty }} ${{ matrix.release }} toolbox image
        uses: docker/build-push-action@v3
        with:
          context: ${{ env.distro }}
          file: ${{ env.distro }}/Containerfile
          platforms: linux/amd64
          push: false
          no-cache: true
          tags: quay.io/toolbx-images/${{ env.distro }}-toolbox:latest
