name: "RHEL: Build toolbx images for PRs"

permissions: read-all

on:
  pull_request:
    branches:
      - main
    paths:
      - rhel/**
      - .github/workflows/rhel-pr.yaml

env:
  distro: 'rhel'
  distro_pretty: 'RHEL'
  latest_release: '9.2'

jobs:
  build-images:
    strategy:
      matrix:
        release: ['8.2', '8.4', '8.6', '8.7', '8.8', '9.0', '9.1', '9.2']

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build ${{ env.distro_pretty }} ${{ matrix.release }} toolbox image
        uses: docker/build-push-action@v3
        with:
          context: ${{ env.distro }}/${{ matrix.release }}
          file: ${{ env.distro }}/${{ matrix.release }}/Containerfile
          platforms: linux/amd64,linux/arm64
          push: false
          no-cache: true
          tags: quay.io/toolbx-images/${{ env.distro }}-toolbox:${{ matrix.release }}
