name: "Ubuntu: Build toolbx images for PRs"

permissions: read-all

on:
  pull_request:
    branches:
      - main
    paths:
      - ubuntu/**
      - .github/workflows/ubuntu-pr.yaml

env:
  distro: 'ubuntu'
  distro_pretty: 'Ubuntu'
  latest_release: '22.04'

jobs:
  build-images:
    strategy:
      matrix:
        release: ['16.04', '18.04', '20.04', '22.04', '22.10']

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build ${{ env.distro_pretty }} ${{ matrix.release }} toolbox image
        uses: docker/build-push-action@v3
        with:
          context: ${{ env.distro }}/${{ matrix.release }}
          file: ${{ env.distro }}/${{ matrix.release }}/Containerfile
          platforms: linux/amd64,linux/arm64
          push: false
          no-cache: true
          tags: quay.io/toolbx-images/${{ env.distro }}-toolbox:${{ matrix.release }}
